import smtplib
import logging
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import List, Dict, Optional
from datetime import datetime

logger = logging.getLogger(__name__)


class EmailNotifier:
    """Send email notifications about store changes"""
    
    def __init__(self, smtp_server: str, smtp_port: int, 
                 username: str, password: str, from_email: str):
        self.smtp_server = smtp_server
        self.smtp_port = smtp_port
        self.username = username
        self.password = password
        self.from_email = from_email

    def send_report(self, recipients: List[str], changes: Dict, 
                   store_counts: Dict, timestamp: Optional[datetime] = None) -> bool:
        """Send email report with store changes and summary
        
        Args:
            recipients: List of email addresses
            changes: Dictionary with change types (from database)
            store_counts: Dictionary with store counts by retailer
            timestamp: Timestamp of the report (default: now)
        
        Returns:
            True if sent successfully
        """
        if not recipients:
            logger.warning("No recipients provided for email notification")
            return False
        
        timestamp = timestamp or datetime.now()
        
        try:
            msg = MIMEMultipart('alternative')
            msg['Subject'] = f"StoreChecker Report - {timestamp.strftime('%Y-%m-%d %H:%M')}"
            msg['From'] = self.from_email
            msg['To'] = ', '.join(recipients)
            
            # Create email body
            html_body = self._create_html_body(changes, store_counts, timestamp)
            text_body = self._create_text_body(changes, store_counts, timestamp)
            
            msg.attach(MIMEText(text_body, 'plain', 'utf-8'))
            msg.attach(MIMEText(html_body, 'html', 'utf-8'))
            
            # Send email
            with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                server.starttls()
                server.login(self.username, self.password)
                server.send_message(msg)
            
            logger.info(f"Email report sent to {', '.join(recipients)}")
            return True
            
        except Exception as e:
            logger.error(f"Failed to send email report: {e}")
            return False

    def _create_text_body(self, changes: Dict, store_counts: Dict, 
                         timestamp: datetime) -> str:
        """Create plain text email body"""
        lines = [
            f"StoreChecker Report - {timestamp.strftime('%Y-%m-%d %H:%M')}",
            "=" * 60,
            ""
        ]
        
        # Changes summary
        if any(changes.values()):
            lines.append("CHANGES DETECTED:")
            lines.append("-" * 60)
            
            if changes.get('new'):
                lines.append(f"\n✓ NEW STORES ({len(changes['new'])})")
                for change in changes['new']:
                    lines.append(f"  - {change['retailer']}: {change['store_id']}")
            
            if changes.get('temporarily_closed'):
                lines.append(f"\n⏸ TEMPORARILY CLOSED ({len(changes['temporarily_closed'])})")
                for change in changes['temporarily_closed']:
                    lines.append(f"  - {change['retailer']}: {change['store_id']}")
            
            if changes.get('permanently_closed'):
                lines.append(f"\n✗ PERMANENTLY CLOSED ({len(changes['permanently_closed'])})")
                for change in changes['permanently_closed']:
                    lines.append(f"  - {change['retailer']}: {change['store_id']}")
            
            if changes.get('reopened'):
                lines.append(f"\n✓ REOPENED ({len(changes['reopened'])})")
                for change in changes['reopened']:
                    lines.append(f"  - {change['retailer']}: {change['store_id']}")
        else:
            lines.append("No changes detected since last report.\n")
        
        # Store count summary
        lines.append("\n" + "-" * 60)
        lines.append("STORE COUNT SUMMARY:")
        lines.append("-" * 60)
        
        for retailer, status, count in store_counts:
            lines.append(f"{retailer:15} {status:20} {count:5}")
        
        lines.append("\n" + "=" * 60)
        lines.append("Generated by StoreChecker")
        
        return "\n".join(lines)

    def _create_html_body(self, changes: Dict, store_counts: Dict, 
                         timestamp: datetime) -> str:
        """Create HTML email body"""
        html = f"""
        <html>
        <head>
            <style>
                body {{ font-family: Arial, sans-serif; margin: 20px; }}
                h1 {{ color: #333; }}
                h2 {{ color: #666; margin-top: 25px; border-bottom: 2px solid #ddd; padding-bottom: 10px; }}
                table {{ border-collapse: collapse; width: 100%; margin-top: 10px; }}
                td, th {{ border: 1px solid #ddd; padding: 10px; text-align: left; }}
                th {{ background-color: #f0f0f0; }}
                .new {{ color: #4CAF50; font-weight: bold; }}
                .temporary {{ color: #FF9800; font-weight: bold; }}
                .permanent {{ color: #F44336; font-weight: bold; }}
                .reopened {{ color: #2196F3; font-weight: bold; }}
                .summary {{ background-color: #f9f9f9; padding: 15px; margin: 15px 0; }}
            </style>
        </head>
        <body>
            <h1>StoreChecker Report</h1>
            <p><strong>Generated:</strong> {timestamp.strftime('%Y-%m-%d %H:%M:%S')}</p>
        """
        
        # Changes section
        if any(changes.values()):
            html += "<h2>Changes Detected</h2>"
            
            if changes.get('new'):
                html += f"""
                <h3 class="new">✓ New Stores ({len(changes['new'])})</h3>
                <table>
                    <tr><th>Retailer</th><th>Store ID</th></tr>
                """
                for change in changes['new']:
                    html += f"<tr><td>{change['retailer']}</td><td>{change['store_id']}</td></tr>"
                html += "</table>"
            
            if changes.get('temporarily_closed'):
                html += f"""
                <h3 class="temporary">⏸ Temporarily Closed ({len(changes['temporarily_closed'])})</h3>
                <table>
                    <tr><th>Retailer</th><th>Store ID</th></tr>
                """
                for change in changes['temporarily_closed']:
                    html += f"<tr><td>{change['retailer']}</td><td>{change['store_id']}</td></tr>"
                html += "</table>"
            
            if changes.get('permanently_closed'):
                html += f"""
                <h3 class="permanent">✗ Permanently Closed ({len(changes['permanently_closed'])})</h3>
                <table>
                    <tr><th>Retailer</th><th>Store ID</th></tr>
                """
                for change in changes['permanently_closed']:
                    html += f"<tr><td>{change['retailer']}</td><td>{change['store_id']}</td></tr>"
                html += "</table>"
            
            if changes.get('reopened'):
                html += f"""
                <h3 class="reopened">✓ Reopened ({len(changes['reopened'])})</h3>
                <table>
                    <tr><th>Retailer</th><th>Store ID</th></tr>
                """
                for change in changes['reopened']:
                    html += f"<tr><td>{change['retailer']}</td><td>{change['store_id']}</td></tr>"
                html += "</table>"
        else:
            html += '<div class="summary"><p>✓ No changes detected since last report.</p></div>'
        
        # Store count summary
        html += """
        <h2>Store Count Summary</h2>
        <table>
            <tr><th>Retailer</th><th>Status</th><th>Count</th></tr>
        """
        
        for retailer, status, count in store_counts:
            html += f"<tr><td>{retailer}</td><td>{status}</td><td>{count}</td></tr>"
        
        html += """
        </table>
        <footer style="margin-top: 30px; padding-top: 15px; border-top: 1px solid #ddd; color: #999; font-size: 12px;">
            <p>Generated by StoreChecker</p>
        </footer>
        </body>
        </html>
        """
        
        return html
